---
title: "Analyse Badges in StackOverflow"
author: "Peter Baumgartner"
date: "`r Sys.Date()`"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
output:
  pdf_document:
    pandoc_args: --number-offset=0,0
    toc: yes
    toc_depth: '4'
    latex_engine: xelatex
  word_document:
    toc: yes
    toc_depth: '4'
  html_notebook:
    fig_caption: yes
    number_sections: yes
    pandoc_args: --number-offset=0,0
    toc: yes
    toc_depth: 4
  github_document:
    toc: yes
    toc_depth: 4
  html_document:
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    pandoc_args: --number-offset=0,0
    toc: yes
    toc_depth: 4
---
```{r label = "global-options", echo=FALSE, highlight=TRUE}
knitr::opts_chunk$set(
        message = F,
        error = F,
        warning = F,
        comment = NA,
        highlight = T,
        prompt = T
        )

### install and load some important packages
### https://github.com/tidyverse/tidyverse
if (!require("tidyverse"))
        {install.packages("tidyverse", repos = 'http://cran.wu.ac.at/')
        library(tidyverse)}

### above command installed and loaded the core tidyverse packages:
# ggplot2: data visualisation
# tibble:  a modern take on data frames
# tidyr:   data tidying
# readr:   data import (csv, tsv, fwf)
# purrr:   functional R programming
# dplyr:   data (frame) manipulation
# stringr: string manipulation
# forcats: working with categorial varialbes

### My personal reminder for other important packages:
### Working with times:
# hms, for times.
# lubridate, for date/times.

### Importing other types of data:
# feather, for sharing with Python and other languages.
# haven, for SPSS, SAS and Stata files.
# httr, for web apis.
# jsonlite for JSON.
# readxl, for .xls and .xlsx files.
# rvest, for web scraping.
# xml2, for XML.

### Modelling
# modelr, for modelling within a pipeline
# broom, for turning models into tidy data
```

```{r install-stackr, eval=FALSE}
devtools::install_github("dgrtwo/stackr", build_vignettes = TRUE)
browseVignettes("stackr")
```

```{r download-badges, eval=FALSE}
library(stackr)
all_badges <- stack_badges(special = "name", pagesize = 100, filter = "!9Z(-x-rJv")
all_badges <- tbl_df(all_badges)
saveRDS(all_badges, file = "data/badges_raw.rds")
```


```{r clean-badges, eval=FALSE}
badges <- readRDS("data/badges_raw.rds")
# shorten very long text in line 51, colum 6
badges[51,6] <- "
Met a Stack Overflow employee at an event where Stack Overflow was an organizer"
# set factor of rank variable (bronze, silver, gold)
badges[, 3] <- as_factor(badges$rank)
badges <- badges[, c(7,4,2,3,6)]
badges <- rename(badges, n = award_count, id = badge_id)
saveRDS(badges, file = "data/badges_clean.rds")
####
# badges_names <- badges[order(badges$name, decreasing = FALSE),]
# write_csv(badges_names, file.path("badges_name.csv"))
# badges_count <- badges[order(badges$n, decreasing = TRUE),]
# write_csv(badges_count, file.path("badges_count.csv"))
# badges_id <- badges[order(badges$id, decreasing = FALSE),]
# write_csv(badges_id, file.path("badges_id.csv"))
```

```{r add-column-activity-as-factor}
badges <- readRDS("data/badges_clean.rds")
activity <-      c(1,5,5,4,3,1,3,5,3,5,
                   4,4,4,3,4,3,3,4,4,1,
                   4,4,4,6,6,6,4,4,2,3,
                   3,4,2,1,3,1,2,2,1,2,
                   1,2,2,5,1,1,3,4,3,2,
                   2,1,5,1,4,3,4,1,2,3,
                   1,4,5,3,3,2,4,2,4,2,
                   1,2,4,1,4,1,4,4,1,4,
                   4,4,4,3,4,2,2,1,2,4,
                   3)
badges <- cbind(badges, activity)
badge_labels <- c(
        "Question",       # 1
        "Answer",         # 2 
        "Participation",  # 3 
        "Moderation",     # 4
        "Other",          # 5
        "Documentation"   # 6
)
badges$activity <- factor(badges$activity, levels = c(1:6), labels = badge_labels)
```
